#!/usr/bin/expect

# Wait for boot
set timeout 30

# Set environment variables
set arch $::env(JHALFS_ARCH)

if { $arch == "x86_64" } {
    set accel "kvm"
} elseif { $arch == "x86_64" } {
    set accel "hvf"
} else {
    puts { "Unsupported architecture: $arch" ; exit 1 }
}

# Start the guest VM
spawn qemu-system-$arch -curses -m 256M -smp 1 -drive file=build_dir.img,format=raw,if=virtio -cpu host -machine type=pc,accel=$accel

expect {
    "login: " { send "root\n" }
    timeout   { puts "Timeout during boot" ; exit 1 }
}

expect "Password: "
send "root\n"

expect "bash"
send "cat /etc/*release | grep PRETTY\n"

expect "Linux From Scratch"
send "shutdown -h now\n"
