services:
  jhalfs:
    container_name: jhalfs
    image: ${JHALFS_IMAGE:-ubuntu:latest}
    privileged: true
    stdin_open: true
    tty: true
    command: >
        sh -c "
        sleep infinity"
    volumes:
      - .:/vagrant
