name: ci

on:
  push:
    branches:
      - '**'
    paths:
      - '!**/**'
      - '.github/workflows/ci.yaml'
      - '*.sh'
      - 'configuration'
      - 'kernel-config'
      - 'Makefile'
  schedule:
    - cron: '0 3 1 * *'  # First day of the month at 3 a.m.

jobs:
  part2:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: docker-compose up
        run: |
          set -eo pipefail
          docker-compose version
          docker-compose up -d
          docker ps

      - name: container up
        # Avoid: the input device is not a TTY
        # https://github.com/actions/runner/issues/241#issuecomment-745902718
        shell: 'script -q -e -c "bash {0}"'
        run: |
          set -eo pipefail
          docker-compose exec jhalfs bash -c "cd /vagrant && bash /vagrant/up.sh"

      - name: fetch jhalfs commit info
        shell: 'script -q -e -c "bash {0}"'
        run: |
          set -eo pipefail
          docker-compose exec jhalfs bash -c "su - vagrant -c 'cd /home/vagrant/jhalfs && git show --oneline --no-abbrev --shortstat'"

      - name: fetch lfs commit info
        shell: 'script -q -e -c "bash {0}"'
        run: |
          set -eo pipefail
          docker-compose exec jhalfs bash -c "su - vagrant -c 'source /vagrant/jhalfs/jhalfs.sh && cd \$LFS/jhalfs/book-source && git show --oneline --no-abbrev --shortstat'"

      - name: disable chapter8 gcc tests
        shell: 'script -q -e -c "bash {0}"'
        run: |
          set -eo pipefail
          docker-compose exec jhalfs bash -c "su - vagrant -c 'source /vagrant/jhalfs/jhalfs.sh && cd \$LFS/jhalfs/lfs-commands/chapter08 && sed -i \"/make -k check/d\" 824-gcc && sed -i \"/test_summary/d\" 824-gcc'"

      - name: force parallel make jobs for the kernel
        shell: 'script -q -e -c "bash {0}"'
        run: |
          set -eo pipefail
          docker-compose exec jhalfs bash -c "su - vagrant -c 'source /vagrant/jhalfs/jhalfs.sh && cd \$LFS/jhalfs/lfs-commands/chapter10 && sed -i \"s|make\$|make -j3|\" 1002-kernel'"

      # The jhalfs directory is assumed to be unchaged from this point, hence caching it once
      # In other words, the $LFS mounted in the guest (container) is assumed invisible (empty dir) to the host
      - name: write cache jhalfs
        uses: actions/cache@v3
        with:
          path: |
            jhalfs
          key: ${{ runner.os }}-${{ github.sha }}-jhalfs

      - name: make ck_UID
        shell: 'script -q -e -c "bash {0}"'
        run: |
          set -eo pipefail
          docker-compose exec jhalfs bash -c "su - vagrant -c 'source /vagrant/jhalfs/jhalfs.sh && cd \$LFS/jhalfs && make $TARGET'"
        env:
          TARGET: ck_UID

      - name: make ck_terminal
        shell: 'script -q -e -c "bash {0}"'
        run: |
          set -eo pipefail
          # Remove ck_terminal target, which fails as below, since it requires an interactive shell.
          # stty: 'standard input': Inappropriate ioctl for device
          # Terminal too small:  columns x  lines
          # Minimum: 80 columns x 24 lines
          docker-compose exec jhalfs bash -c "su - vagrant -c 'source /vagrant/jhalfs/jhalfs.sh && cd \$LFS/jhalfs && sed -i \"/^all:/s/$TARGET//\" Makefile'"
          exit
          docker-compose exec jhalfs bash -c "su - vagrant -c 'source /vagrant/jhalfs/jhalfs.sh && cd \$LFS/jhalfs && make $TARGET'"
        env:
          TARGET: ck_terminal

      - name: make mk_SETUP
        shell: 'script -q -e -c "bash {0}"'
        run: |
          set -eo pipefail
          docker-compose exec jhalfs bash -c "su - vagrant -c 'source /vagrant/jhalfs/jhalfs.sh && cd \$LFS/jhalfs && make $TARGET'"
        env:
          TARGET: mk_SETUP

      - name: save jhalfs:part2 image
        run: |
          set -eo pipefail
          docker commit -m "II. Preparing for the Build" jhalfs jhalfs:part2
          docker save jhalfs:part2 > jhalfs.tar
          docker stop jhalfs
          docker rm jhalfs
          docker images
          docker ps

      # https://github.com/actions/cache/issues/2 - no way to update the cache - use suffix
      - name: write cache jhalfs.tar
        uses: actions/cache@v3
        with:
          path: |
            jhalfs.tar
          key: ${{ runner.os }}-${{ github.sha }}-jhalfs.tar.part2

      - name: write cache build_dir.img
        uses: actions/cache@v3
        with:
          path: |
            build_dir.img
          key: ${{ runner.os }}-${{ github.sha }}-build_dir.img.part2

  part3luser:
    needs: part2
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: read cache jhalfs
        uses: actions/cache@v3
        with:
          path: |
            jhalfs
          key: ${{ runner.os }}-${{ github.sha }}-jhalfs

      - name: read cache jhalfs.tar
        uses: actions/cache@v3
        with:
          path: |
            jhalfs.tar
          key: ${{ runner.os }}-${{ github.sha }}-jhalfs.tar.part2

      - name: read cache build_dir.img
        uses: actions/cache@v3
        with:
          path: |
            build_dir.img
          key: ${{ runner.os }}-${{ github.sha }}-build_dir.img.part2

      - name: load jhalfs:part2 image
        run: |
          set -eo pipefail
          docker load < jhalfs.tar
          JHALFS_IMAGE=jhalfs:part2 docker-compose up -d
          docker images
          docker ps

      - name: attach and mount loopback
        shell: 'script -q -e -c "bash {0}"'
        run: |
          set -eo pipefail
          docker-compose exec jhalfs bash -c "losetup \$(cat /vagrant/jhalfs/build_dir.dev) /vagrant/build_dir.img && mount -a"

      - name: make mk_LUSER
        shell: 'script -q -e -c "bash {0}"'
        run: |
          set -eo pipefail
          docker-compose exec jhalfs bash -c "su - vagrant -c 'source /vagrant/jhalfs/jhalfs.sh && cd \$LFS/jhalfs && make $TARGET'"
        env:
          TARGET: mk_LUSER

      - name: save jhalfs:part3luser image
        run: |
          set -eo pipefail
          docker commit -m "III. Building the LFS Cross Toolchain and Temporary Tools" jhalfs jhalfs:part3luser
          docker save jhalfs:part3luser > jhalfs.tar
          docker stop jhalfs
          docker rm jhalfs
          docker images
          docker ps

      - name: write cache jhalfs.tar
        uses: actions/cache@v3
        with:
          path: |
            jhalfs.tar
          key: ${{ runner.os }}-${{ github.sha }}-jhalfs.tar.part3luser

      - name: write cache build_dir.img
        uses: actions/cache@v3
        with:
          path: |
            build_dir.img
          key: ${{ runner.os }}-${{ github.sha }}-build_dir.img.part3luser

  part3shadow:
    needs: part3luser
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: read cache jhalfs
        uses: actions/cache@v3
        with:
          path: |
            jhalfs
          key: ${{ runner.os }}-${{ github.sha }}-jhalfs

      - name: read cache jhalfs.tar
        uses: actions/cache@v3
        with:
          path: |
            jhalfs.tar
          key: ${{ runner.os }}-${{ github.sha }}-jhalfs.tar.part3luser

      - name: read cache build_dir.img
        uses: actions/cache@v3
        with:
          path: |
            build_dir.img
          key: ${{ runner.os }}-${{ github.sha }}-build_dir.img.part3luser

      - name: load jhalfs:part3luser image
        run: |
          set -eo pipefail
          docker load < jhalfs.tar
          JHALFS_IMAGE=jhalfs:part3luser docker-compose up -d
          docker images
          docker ps

      - name: attach and mount loopback
        shell: 'script -q -e -c "bash {0}"'
        run: |
          set -eo pipefail
          docker-compose exec jhalfs bash -c "losetup \$(cat /vagrant/jhalfs/build_dir.dev) /vagrant/build_dir.img && mount -a"

      - name: make mk_SUDO
        shell: 'script -q -e -c "bash {0}"'
        run: |
          set -eo pipefail
          docker-compose exec jhalfs bash -c "su - vagrant -c 'source /vagrant/jhalfs/jhalfs.sh && cd \$LFS/jhalfs && make $TARGET'"
        env:
          TARGET: mk_SUDO

      - name: make BREAKPOINT=823-shadow
        shell: 'script -q -e -c "bash {0}"'
        run: |
          set -eo pipefail
          # https://lists.linuxfromscratch.org/sympa/arc/alfs-discuss/2022-09/msg00015.html
          docker-compose exec jhalfs bash -c "su - vagrant -c 'source /vagrant/jhalfs/jhalfs.sh && cd \$LFS/jhalfs && make $TARGET'"
        env:
          TARGET: BREAKPOINT=823-shadow

      - name: save jhalfs:part3shadow image
        run: |
          set -eo pipefail
          docker commit -m "III. Building the LFS Cross Toolchain and Temporary Tools" jhalfs jhalfs:part3shadow
          docker save jhalfs:part3shadow > jhalfs.tar
          docker stop jhalfs
          docker rm jhalfs
          docker images
          docker ps

      - name: write cache jhalfs.tar
        uses: actions/cache@v3
        with:
          path: |
            jhalfs.tar
          key: ${{ runner.os }}-${{ github.sha }}-jhalfs.tar.part3shadow

      - name: write cache build_dir.img
        uses: actions/cache@v3
        with:
          path: |
            build_dir.img
          key: ${{ runner.os }}-${{ github.sha }}-build_dir.img.part3shadow

  part3gcc:
    needs: part3shadow
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: read cache jhalfs
        uses: actions/cache@v3
        with:
          path: |
            jhalfs
          key: ${{ runner.os }}-${{ github.sha }}-jhalfs

      - name: read cache jhalfs.tar
        uses: actions/cache@v3
        with:
          path: |
            jhalfs.tar
          key: ${{ runner.os }}-${{ github.sha }}-jhalfs.tar.part3shadow

      - name: read cache build_dir.img
        uses: actions/cache@v3
        with:
          path: |
            build_dir.img
          key: ${{ runner.os }}-${{ github.sha }}-build_dir.img.part3shadow

      - name: load jhalfs:part3shadow image
        run: |
          set -eo pipefail
          docker load < jhalfs.tar
          JHALFS_IMAGE=jhalfs:part3shadow docker-compose up -d
          docker images
          docker ps

      - name: attach and mount loopback
        shell: 'script -q -e -c "bash {0}"'
        run: |
          set -eo pipefail
          docker-compose exec jhalfs bash -c "losetup \$(cat /vagrant/jhalfs/build_dir.dev) /vagrant/build_dir.img && mount -a"

      - name: make BREAKPOINT=824-gcc
        shell: 'script -q -e -c "bash {0}"'
        run: |
          set -eo pipefail
          # https://lists.linuxfromscratch.org/sympa/arc/alfs-discuss/2022-09/msg00015.html
          docker-compose exec jhalfs bash -c "su - vagrant -c 'source /vagrant/jhalfs/jhalfs.sh && cd \$LFS/jhalfs && make $TARGET'"
        env:
          TARGET: BREAKPOINT=824-gcc

      - name: save jhalfs:part3gcc image
        run: |
          set -eo pipefail
          docker commit -m "III. Building the LFS Cross Toolchain and Temporary Tools" jhalfs jhalfs:part3gcc
          docker save jhalfs:part3gcc > jhalfs.tar
          docker stop jhalfs
          docker rm jhalfs
          docker images
          docker ps

      - name: write cache jhalfs.tar
        uses: actions/cache@v3
        with:
          path: |
            jhalfs.tar
          key: ${{ runner.os }}-${{ github.sha }}-jhalfs.tar.part3gcc

      - name: write cache build_dir.img
        uses: actions/cache@v3
        with:
          path: |
            build_dir.img
          key: ${{ runner.os }}-${{ github.sha }}-build_dir.img.part3gcc

  part3:
    needs: part3gcc
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: read cache jhalfs
        uses: actions/cache@v3
        with:
          path: |
            jhalfs
          key: ${{ runner.os }}-${{ github.sha }}-jhalfs

      - name: read cache jhalfs.tar
        uses: actions/cache@v3
        with:
          path: |
            jhalfs.tar
          key: ${{ runner.os }}-${{ github.sha }}-jhalfs.tar.part3gcc

      - name: read cache build_dir.img
        uses: actions/cache@v3
        with:
          path: |
            build_dir.img
          key: ${{ runner.os }}-${{ github.sha }}-build_dir.img.part3gcc

      - name: load jhalfs:part3gcc image
        run: |
          set -eo pipefail
          docker load < jhalfs.tar
          JHALFS_IMAGE=jhalfs:part3gcc docker-compose up -d
          docker images
          docker ps

      - name: attach and mount loopback
        shell: 'script -q -e -c "bash {0}"'
        run: |
          set -eo pipefail
          docker-compose exec jhalfs bash -c "losetup \$(cat /vagrant/jhalfs/build_dir.dev) /vagrant/build_dir.img && mount -a"

      - name: make mk_CHROOT
        shell: 'script -q -e -c "bash {0}"'
        run: |
          set -eo pipefail
          # https://lists.linuxfromscratch.org/sympa/arc/alfs-discuss/2022-09/msg00015.html
          docker-compose exec jhalfs bash -c "su - vagrant -c 'source /vagrant/jhalfs/jhalfs.sh && cd \$LFS/jhalfs && make $TARGET'"
        env:
          TARGET: mk_CHROOT

      - name: save jhalfs:part3 image
        run: |
          set -eo pipefail
          docker commit -m "III. Building the LFS Cross Toolchain and Temporary Tools" jhalfs jhalfs:part3
          docker save jhalfs:part3 > jhalfs.tar
          docker stop jhalfs
          docker rm jhalfs
          docker images
          docker ps

      - name: write cache jhalfs.tar
        uses: actions/cache@v3
        with:
          path: |
            jhalfs.tar
          key: ${{ runner.os }}-${{ github.sha }}-jhalfs.tar.part3

      - name: write cache build_dir.img
        uses: actions/cache@v3
        with:
          path: |
            build_dir.img
          key: ${{ runner.os }}-${{ github.sha }}-build_dir.img.part3

  part4:
    needs: part3
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: read cache jhalfs
        uses: actions/cache@v3
        with:
          path: |
            jhalfs
          key: ${{ runner.os }}-${{ github.sha }}-jhalfs

      - name: read cache jhalfs.tar
        uses: actions/cache@v3
        with:
          path: |
            jhalfs.tar
          key: ${{ runner.os }}-${{ github.sha }}-jhalfs.tar.part3

      - name: read cache build_dir.img
        uses: actions/cache@v3
        with:
          path: |
            build_dir.img
          key: ${{ runner.os }}-${{ github.sha }}-build_dir.img.part3

      - name: load jhalfs:part3 image
        run: |
          set -eo pipefail
          docker load < "jhalfs:part3.tar"
          JHALFS_IMAGE=jhalfs:part3 docker-compose up -d
          docker images
          docker ps

      - name: attach and mount loopback
        shell: 'script -q -e -c "bash {0}"'
        run: |
          set -eo pipefail
          docker-compose exec jhalfs bash -c "losetup \$(cat /vagrant/jhalfs/build_dir.dev) /vagrant/build_dir.img && mount -a"

      - name: make mk_BOOT
        shell: 'script -q -e -c "bash {0}"'
        run: |
          set -eo pipefail
          docker-compose exec jhalfs bash -c "su - vagrant -c 'source /vagrant/jhalfs/jhalfs.sh && cd \$LFS/jhalfs && make $TARGET'"
        env:
          TARGET: mk_BOOT

      - name: make create-sbu_du-report
        shell: 'script -q -e -c "bash {0}"'
        run: |
          set -eo pipefail
          docker-compose exec jhalfs bash -c "su - vagrant -c 'source /vagrant/jhalfs/jhalfs.sh && cd \$LFS/jhalfs && make $TARGET'"
        env:
          TARGET: create-sbu_du-report

      - name: save jhalfs:part4 image
        run: |
          set -eo pipefail
          docker commit -m "IV. Building the LFS System" jhalfs jhalfs:part4
          docker save jhalfs:part4 > jhalfs.tar
          #docker stop jhalfs  # This is the last part of the book run, don't stop the container
          #docker rm jhalfs
          docker images
          docker ps

      - name: write cache jhalfs.tar
        uses: actions/cache@v3
        with:
          path: |
            jhalfs.tar
          key: ${{ runner.os }}-${{ github.sha }}-jhalfs.tar.part4

      - name: write cache build_dir.img
        uses: actions/cache@v3
        with:
          path: |
            build_dir.img
          key: ${{ runner.os }}-${{ github.sha }}-build_dir.img.part4

      - name: print SBUs report
        shell: 'script -q -e -c "bash {0}"'
        run: |
          set -eo pipefail
          docker-compose exec jhalfs bash -c "su - vagrant -c 'source /vagrant/jhalfs/jhalfs.sh && cat \$LFS/jhalfs/*SBU_DU*.report'"

      - name: make mk_BLFS_TOOL
        shell: 'script -q -e -c "bash {0}"'
        run: |
          set -eo pipefail
          docker-compose exec jhalfs bash -c "su - vagrant -c 'source /vagrant/jhalfs/jhalfs.sh && cd \$LFS/jhalfs && make $TARGET'"
        env:
          TARGET: mk_BLFS_TOOL

      - name: make mk_CUSTOM_TOOLS
        shell: 'script -q -e -c "bash {0}"'
        run: |
          set -eo pipefail
          docker-compose exec jhalfs bash -c "su - vagrant -c 'source /vagrant/jhalfs/jhalfs.sh && cd \$LFS/jhalfs && make $TARGET'"
        env:
          TARGET: mk_CUSTOM_TOOLS
