name: ci

on:
  push:
    branches:
      - '**'
    paths:
      - '!**/**'
      - '.github/ci.yaml'
      - '*.sh'
      - 'Makefile'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: docker-compose up
        run: |
          set -eo pipefail
          docker-compose version
          docker-compose up -d
          docker ps

      - name: container up
        run: |
          set -eo pipefail
          docker-compose exec -T jhalfs bash -c "cd /vagrant && bash /vagrant/up.sh"

      - name: fetch jhalfs commit info
        run: |
          set -eo pipefail
          docker-compose exec -T jhalfs bash -c "su - vagrant -c 'cd /home/vagrant/jhalfs && git show --oneline --no-abbrev --shortstat'"

      - name: fetch lfs commit info
        run: |
          set -eo pipefail
          docker-compose exec -T jhalfs bash -c "su - vagrant -c 'source /vagrant/jhalfs/jhalfs.sh && cd \$LFS/jhalfs/book-source && git show --oneline --no-abbrev --shortstat'"

      - name: configure parallel make jobs
        run: |
          set -eo pipefail
          docker-compose exec -T jhalfs bash -c "su - vagrant -c 'source /vagrant/jhalfs/jhalfs.sh && cd \$LFS/jhalfs && for file in \$(find lfs-commands -name \"*gcc*\" -o -name \"*glibc*\"); do echo \$file && sed -i \"s/make -j./make -j2/\" \$file; done'"

      - name: make ck_UID
        run: |
          set -eo pipefail
          docker-compose exec -T jhalfs bash -c "su - vagrant -c 'source /vagrant/jhalfs/jhalfs.sh && cd \$LFS/jhalfs && make $TARGET'"
        env:
          TARGET: ck_UID

      - name: make ck_terminal
        run: |
          set -eo pipefail
          # Exclude ck_terminal target, which fails with:
          # stty: 'standard input': Inappropriate ioctl for device
          # Terminal too small:  columns x  lines
          # Minimum: 80 columns x 24 lines
          exit 0
          docker-compose exec -T jhalfs bash -c "su - vagrant -c 'source /vagrant/jhalfs/jhalfs.sh && cd \$LFS/jhalfs && make $TARGET'"
        env:
          TARGET: ck_terminal

      - name: make mk_SETUP
        run: |
          set -eo pipefail
          docker-compose exec -T jhalfs bash -c "su - vagrant -c 'source /vagrant/jhalfs/jhalfs.sh && cd \$LFS/jhalfs && make $TARGET'"
        env:
          TARGET: mk_SETUP

      - name: make mk_LUSER
        run: |
          set -eo pipefail
          docker-compose exec -T jhalfs bash -c "su - vagrant -c 'source /vagrant/jhalfs/jhalfs.sh && cd \$LFS/jhalfs && make $TARGET'"
        env:
          TARGET: mk_LUSER

      - name: make mk_SUDO
        run: |
          set -eo pipefail
          docker-compose exec -T jhalfs bash -c "su - vagrant -c 'source /vagrant/jhalfs/jhalfs.sh && cd \$LFS/jhalfs && make $TARGET'"
        env:
          TARGET: mk_SUDO

      - name: make mk_CHROOT
        run: |
          set -eo pipefail
          docker-compose exec -T jhalfs bash -c "su - vagrant -c 'source /vagrant/jhalfs/jhalfs.sh && cd \$LFS/jhalfs && make $TARGET'"
        env:
          TARGET: mk_CHROOT mk_BOOT create-sbu_du-report mk_BLFS_TOOL mk_CUSTOM_TOOLS

      - name: make mk_BOOT
        run: |
          set -eo pipefail
          docker-compose exec -T jhalfs bash -c "su - vagrant -c 'source /vagrant/jhalfs/jhalfs.sh && cd \$LFS/jhalfs && make $TARGET'"
        env:
          TARGET: mk_BOOT

      - name: make create-sbu_du-report
        run: |
          set -eo pipefail
          docker-compose exec -T jhalfs bash -c "su - vagrant -c 'source /vagrant/jhalfs/jhalfs.sh && cd \$LFS/jhalfs && make $TARGET'"
        env:
          TARGET: create-sbu_du-report

      - name: make mk_BLFS_TOOL
        run: |
          set -eo pipefail
          docker-compose exec -T jhalfs bash -c "su - vagrant -c 'source /vagrant/jhalfs/jhalfs.sh && cd \$LFS/jhalfs && make $TARGET'"
        env:
          TARGET: mk_BLFS_TOOL

      - name: make mk_CUSTOM_TOOLS
        run: |
          set -eo pipefail
          docker-compose exec -T jhalfs bash -c "su - vagrant -c 'source /vagrant/jhalfs/jhalfs.sh && cd \$LFS/jhalfs && make $TARGET'"
        env:
          TARGET: mk_CUSTOM_TOOLS
